import * as WebAudio from 'node-web-audio-api';
for (const [k, v] of Object.entries(WebAudio)) if (typeof v === 'function' && !globalThis[k]) globalThis[k] = v;
const ac = new WebAudio.AudioContext();
const g = ac.createGain();
console.log('globalThis.AudioParam === WebAudio.AudioParam:', globalThis.AudioParam === WebAudio.AudioParam);
console.log('gain instanceof globalThis.AudioParam:', g.gain instanceof globalThis.AudioParam);
console.log('gain instanceof WebAudio.AudioParam:', g.gain instanceof WebAudio.AudioParam);
const Tone = (await import('tone')).default;
console.log('after tone import, gain instanceof globalThis.AudioParam:', g.gain instanceof globalThis.AudioParam);
console.log('after tone import, gain instanceof WebAudio.AudioParam:', g.gain instanceof WebAudio.AudioParam);
setTimeout(() => process.exit(0), 300);
